# Generated by Django 4.1.3 on 2024-06-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='subject name:'),
        ),
    ]
